/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author luthfy
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    boolean a=true;
    public DashboardView() {
        initComponents();
        
        String kata = "DI APLIKASI HR\n wkwkwk \n kelompok: \n 1. petrik\n 2. markonah";
        
        txtContent.setText(kata.replaceAll("<","&lt;").replaceAll(">", "&gt;").replaceAll("\n", "<br/>") + "<html>" + "</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        maxminclose = new javax.swing.JPanel();
        buttonclose = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonmax = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonmin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuicon = new javax.swing.JPanel();
        buttonburger = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        listmenu = new javax.swing.JPanel();
        buttonGlass1 = new komponen.ButtonGlass();
        buttonGlass2 = new komponen.ButtonGlass();
        buttonGlass3 = new komponen.ButtonGlass();
        buttonGlass4 = new komponen.ButtonGlass();
        buttonGlass5 = new komponen.ButtonGlass();
        buttonGlass6 = new komponen.ButtonGlass();
        dashboard = new javax.swing.JPanel();
        panelbody = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtContent = new javax.swing.JLabel();
        pnl_overlay = new javax.swing.JPanel();
        lbl_nav2 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setUndecorated(true);
        setResizable(false);

        header.setBackground(new java.awt.Color(31, 91, 137));
        header.setPreferredSize(new java.awt.Dimension(800, 50));

        maxminclose.setBackground(new java.awt.Color(31, 91, 137));
        maxminclose.setPreferredSize(new java.awt.Dimension(145, 50));
        maxminclose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonclose.setBackground(new java.awt.Color(31, 91, 137));
        buttonclose.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonclose.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close_window_32px.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        buttonclose.add(jLabel2, java.awt.BorderLayout.CENTER);

        maxminclose.add(buttonclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 50));

        buttonmax.setBackground(new java.awt.Color(31, 91, 137));
        buttonmax.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonmax.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/maximize_window_32px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        buttonmax.add(jLabel1, java.awt.BorderLayout.CENTER);

        maxminclose.add(buttonmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 50));

        buttonmin.setBackground(new java.awt.Color(31, 91, 137));
        buttonmin.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonmin.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minimize_window_32px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        buttonmin.add(jLabel3, java.awt.BorderLayout.CENTER);

        maxminclose.add(buttonmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(793, Short.MAX_VALUE)
                .addComponent(maxminclose, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maxminclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(102, 153, 255));
        menu.setPreferredSize(new java.awt.Dimension(270, 600));
        menu.setLayout(new java.awt.BorderLayout());

        menuicon.setBackground(new java.awt.Color(31, 91, 137));
        menuicon.setPreferredSize(new java.awt.Dimension(50, 600));
        menuicon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonburger.setBackground(new java.awt.Color(31, 91, 137));
        buttonburger.setPreferredSize(new java.awt.Dimension(50, 50));
        buttonburger.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back_window_32px.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        buttonburger.add(jLabel4, java.awt.BorderLayout.CENTER);

        menuicon.add(buttonburger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menu.add(menuicon, java.awt.BorderLayout.LINE_START);

        listmenu.setBackground(new java.awt.Color(63, 119, 188));
        listmenu.setPreferredSize(new java.awt.Dimension(270, 600));
        listmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGlass1.setForeground(new java.awt.Color(255, 255, 255));
        buttonGlass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home_24px.png"))); // NOI18N
        buttonGlass1.setText("Menu4");
        buttonGlass1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonGlass1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        listmenu.add(buttonGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 50));

        buttonGlass2.setForeground(new java.awt.Color(255, 255, 255));
        buttonGlass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/about_24px.png"))); // NOI18N
        buttonGlass2.setText("ABOUT");
        buttonGlass2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonGlass2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        listmenu.add(buttonGlass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 220, 50));

        buttonGlass3.setForeground(new java.awt.Color(255, 255, 255));
        buttonGlass3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/master_25px.png"))); // NOI18N
        buttonGlass3.setText("Data Master");
        buttonGlass3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        buttonGlass3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonGlass3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonGlass3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGlass3ActionPerformed(evt);
            }
        });
        listmenu.add(buttonGlass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, 50));

        buttonGlass4.setForeground(new java.awt.Color(255, 255, 255));
        buttonGlass4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/transaction_25px.png"))); // NOI18N
        buttonGlass4.setText("Transaksi");
        buttonGlass4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonGlass4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonGlass4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGlass4ActionPerformed(evt);
            }
        });
        listmenu.add(buttonGlass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 220, 50));

        buttonGlass5.setForeground(new java.awt.Color(255, 255, 255));
        buttonGlass5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/report_file_25px.png"))); // NOI18N
        buttonGlass5.setText("Report");
        buttonGlass5.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonGlass5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonGlass5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGlass5ActionPerformed(evt);
            }
        });
        listmenu.add(buttonGlass5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 50));

        buttonGlass6.setForeground(new java.awt.Color(255, 255, 255));
        buttonGlass6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home_24px.png"))); // NOI18N
        buttonGlass6.setText("Menu3");
        buttonGlass6.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        buttonGlass6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        listmenu.add(buttonGlass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 220, 50));

        menu.add(listmenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        dashboard.setBackground(new java.awt.Color(255, 255, 255));

        panelbody.setBackground(new java.awt.Color(234, 236, 238));
        panelbody.setPreferredSize(new java.awt.Dimension(1220, 596));
        panelbody.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setText("SELAMAT DATANG");

        txtContent.setText("DI APLIKASI PENGGAJIAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(435, Short.MAX_VALUE))
        );

        panelbody.add(jPanel2, java.awt.BorderLayout.CENTER);

        pnl_overlay.setBackground(new java.awt.Color(204, 212, 233));
        pnl_overlay.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        lbl_nav2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbl_nav2.setText("Home");

        javax.swing.GroupLayout pnl_overlayLayout = new javax.swing.GroupLayout(pnl_overlay);
        pnl_overlay.setLayout(pnl_overlayLayout);
        pnl_overlayLayout.setHorizontalGroup(
            pnl_overlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_overlayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nav2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_overlayLayout.setVerticalGroup(
            pnl_overlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_overlayLayout.createSequentialGroup()
                .addComponent(lbl_nav2)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_overlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelbody, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnl_overlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelbody, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
        );

        getContentPane().add(dashboard, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(31, 91, 137));
        footer.setInheritsPopupMenu(true);
        footer.setPreferredSize(new java.awt.Dimension(1236, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("copyright@kelompok1_R63");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(823, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(footer, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(31, 91, 137));
        jPanel1.setPreferredSize(new java.awt.Dimension(10, 659));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void changecolor(JPanel hover, Color color){
        hover.setBackground(color);
    }
    
    public void changeimage(JLabel button, String resourcheimage){
        ImageIcon img = new ImageIcon(getClass().getResource(resourcheimage));
        button.setIcon(img);
    }
    
    public void showhide(JPanel showhide, boolean dashboard, JLabel button){
        if(dashboard == true){
            showhide.setPreferredSize(new Dimension(50, showhide.getHeight()));
            changeimage(button, "/Icon/burger_32px.png");
        }else{
            showhide.setPreferredSize(new Dimension(270, showhide.getHeight())); 
            changeimage(button, "/Icon/back_window_32px.png");
        }
    }
    
    public void showhidepanel(JPanel showhide, boolean dashboard){
        if(dashboard == true){
            showhide.setPreferredSize(new Dimension(0, showhide.getHeight()));
        }else{
            showhide.setPreferredSize(new Dimension(0, showhide.getHeight()));
        }
    }
    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        changecolor(buttonclose, new Color(25, 29, 74));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        changecolor(buttonclose, new Color(31,91,137));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        setState(DashboardView.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
         changecolor(buttonmin, new Color(25, 29, 74));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        changecolor(buttonmin, new Color(31,91,137));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(this.getExtendedState() != DashboardView.MAXIMIZED_BOTH){
            this.setExtendedState(DashboardView.MAXIMIZED_BOTH);
        }else{
            this.setExtendedState(DashboardView.NORMAL);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
         changecolor(buttonmax, new Color(25, 29, 74));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
           changecolor(buttonmax, new Color(31,91,137));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if(a==true){
            showhide(menu, a, jLabel4);
            SwingUtilities.updateComponentTreeUI(this);
            a=false;
        }else{
            showhide(menu, a, jLabel4);
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        changecolor(buttonburger, new Color(25, 29, 74));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
         changecolor(buttonburger, new Color(31,91,137));
    }//GEN-LAST:event_jLabel4MouseExited

    private void buttonGlass3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGlass3ActionPerformed
                
        pnl_overlay.setBackground(new Color(143,176,226));
        lbl_nav2.setText("Data Master");
        
        
        panelbody.removeAll();
        panelbody.revalidate();
        panelbody.repaint();
        panelbody.add(new DataMasterPanel());
    }//GEN-LAST:event_buttonGlass3ActionPerformed

    private void buttonGlass4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGlass4ActionPerformed
        pnl_overlay.setBackground(new Color(143,176,226));
        lbl_nav2.setText("Transaksi");
        
        
        panelbody.removeAll();
        panelbody.revalidate();
        panelbody.repaint();
        panelbody.add(new FormTransaksiPanel());
    }//GEN-LAST:event_buttonGlass4ActionPerformed

    private void buttonGlass5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGlass5ActionPerformed
      
    }//GEN-LAST:event_buttonGlass5ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Macintosh".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashboardView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private komponen.ButtonGlass buttonGlass1;
    private komponen.ButtonGlass buttonGlass2;
    private komponen.ButtonGlass buttonGlass3;
    private komponen.ButtonGlass buttonGlass4;
    private komponen.ButtonGlass buttonGlass5;
    private komponen.ButtonGlass buttonGlass6;
    private javax.swing.JPanel buttonburger;
    private javax.swing.JPanel buttonclose;
    private javax.swing.JPanel buttonmax;
    private javax.swing.JPanel buttonmin;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_nav2;
    private javax.swing.JPanel listmenu;
    private javax.swing.JPanel maxminclose;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuicon;
    private javax.swing.JPanel panelbody;
    private javax.swing.JPanel pnl_overlay;
    private javax.swing.JLabel txtContent;
    // End of variables declaration//GEN-END:variables
}
